### ISSUE TITLE
dynamic mesh technique

### ISSUE THREAD

**Issue by sasankheirandish** [fppimenta/rheoTool#12]
Dear Francisco Pimenta
I want to use both DynamicRefineFvMesh and dynamicMotionSolverFvMesh techniques together in  rheoInterFoam solver. How can I write these functions together in DynamicMeshDict file?  I tried many solutions,  but all of the solutions used only one of the techniques, however I want use both of them together. How can I solve my problem?
Best regards

**Comment by fppimenta** [comment]
Well this is a question related with generic OpenFOAM, because rheoInterFoam simply uses the built-in engine for mesh motion. From what I see here: https://github.com/OpenFOAM/OpenFOAM-6/tree/master/src/dynamicFvMesh, dynamicMotionSolverFvMesh and dynamicRefineFvMesh are derived from the same base class and are mutually exclusive. Therefore, as the code is you cannot use both. You would need to hack the code. Not sure if this also applies to foam-extend (the mesh motion engine is more advanced there).
