### ISSUE TITLE
install petsc on mac

### ISSUE THREAD

**Issue by Manoochehrb** [fppimenta/rheoTool#15]
when i want install rheotool on mac os i find a problem 
Petsc has been downloaded successfully to directory:

/home/openfoam/ThirdParty/petsc-3.10.2

./installPetsc: 121: ./installPetsc: sudo: not found
./installPetsc: 122: ./installPetsc: sudo: not found
./installPetsc: 123: ./installPetsc: sudo: not found
./installPetsc: 124: ./installPetsc: sudo: not found
/usr/bin/env: 'python': No such file or directory
how can i fi it?pleaswe help

**Comment by Manoochehrb** [comment]
how can i fi it?please help

**Comment by Manoochehrb** [comment]
how can i fix it?

**Comment by Manoochehrb** [comment]
and when i run command ./allwmake 
In file included from segregated/hypreSolver/hypreSolver.H:38:0,
                 from segregated/hypreSolver/hypreSolvers.C:26:
lnInclude/HypreIJSolver.H:43:10: fatal error: HYPRE_krylov.h: No such file or directory
 #include <HYPRE_krylov.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
/opt/openfoam6/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/segregated/hypreSolver/hypreSolvers.o' failed
make: *** [Make/linux64GccDPInt32Opt/segregated/hypreSolver/hypreSolvers.o] Error 1

**Comment by Manoochehrb** [comment]
please help me

**Comment by fppimenta** [comment]
RheoTool is built and tested based on Linux OS. I cannot provide support for mac OS, but I can suggest a few things.

Option 1:
The error when you run Allwmake is simply because Petsc is not installed. So you need first to install Petsc in your OS and, since script ./installPetsc seems not be helping, you will need to do it manually. This shall not be too difficult and you can google it on the web. When you ./configure Petsc, be sure to include the options specified in ./installPetsc, since some are essential for rheoTool (others are optional). Also, do not forget at the end to define/export env vars PETSC_DIR, PETSC_ARCH and LD_LIBRARY_PATH. 

Option 2: 
Install a virtual machine in your macos and run openfoam and rheotool from there in a ubuntu OS.

Option 3:
If coupled solvers are not important for you, install the previous version of rheoTool (3.0), which you can find in the latest release: 
https://github.com/fppimenta/rheoTool/archive/v3.0.tar.gz
This version does not requires Petsc, so if you can install & run openfoam (4.0 or 6.0) in your mac, then you will also be able to  install & run rheoTool. However, no coupled solvers.

**Comment by Manoochehrb** [comment]
thanks for your help
when i want compile i have this error
OpenFOAM-6(44) ./Allwmake -j 4
Compiling enabled on 4 cores
Allwmake /home/openfoam/of60/src
./Allwmake: 7: ./Allwmake: ./Allwmake: Permission denied

**Comment by Manoochehrb** [comment]
i am installing rheotool 3 and above error become

**Comment by Manoochehrb** [comment]
in the first option ./configure not working and command not found apear
https://www.mcs.anl.gov/petsc/documentation/installation.html.

**Comment by Manoochehrb** [comment]
bash: ./configure: No such file or directory

**Comment by Manoochehrb** [comment]
can u help me by online apps like anydesk and connect with my mac?im phd student and i need rheotool for my thesis

**Comment by fppimenta** [comment]
About the Allwmake error, it seems you don't have admin privilege. Either sudo chmod the script or simply run:

sudo ./Allwmake -j 4

About the ./configure of Petsc, it is not that simple in macos. You should follow specific instructions for macos, which are not given in the page you mention. You can find them elsewhere.

**Comment by Manoochehrb** [comment]
OpenFOAM-6(55) sudo ./Allwmake -j 4
bash: sudo: command not found

**Comment by Manoochehrb** [comment]
i cant find petsc on mac in web.i doesnt exist

**Comment by fppimenta** [comment]
About the error, something is wrong with your system, not with rheoTool. I suggest this as a first approach:

https://apple.stackexchange.com/questions/282299/sudo-command-not-found

How did you install openfoam 6.0?

About Petsc in macos, yes it does exist. Just look better.

**Comment by Manoochehrb** [comment]
I installed virtualbox and installing ubuntu and openfoam6 and install petsc but when i compile and run ./Allwmake i have an error

**Comment by Manoochehrb** [comment]
![ca5843b2-f72a-4350-98e4-cf60d6b21d22](https://user-images.githubusercontent.com/36324383/59123435-7a247f00-8972-11e9-8383-9e6f78f5f88f.jpg)

**Comment by fppimenta** [comment]
The error tells you that Hypre was not found. Since Hypre comes with Petsc, then Petsc was not correctly installed. You can confirm that by running these commands in the SAME terminal where you run Allwmake:

echo $LD_LIBRARY_PATH
echo $PETSC_DIR
echo PETSC_ARCH

Please post the output.

**Comment by Manoochehrb** [comment]
Thanks for your help
Its done
I can run rheotool
Thank u
