### ISSUE TITLE
Steady-state solution of 1D Ion-exchange membrane

### ISSUE THREAD

**Issue by Beramos** [fppimenta/rheoTool#2]
Any idea why a floating point exception is thrown when trying to solve the 1D case for the ion-exchange membrane when setting ddt scheme to steady-state? 

**Output:**
``` Bash
Running rheoEFoam in solution1D and ouputing to null.
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#3  double Foam::sumProd<double>(Foam::UList<double> const&, Foam::UList<double> const&) at ??:?
#4  Foam::PBiCG::solve(Foam::Field<double>&, Foam::Field<double> const&, unsigned char) const at ??:?
#5  Foam::fvMatrix<double>::solveSegregated(Foam::dictionary const&) at ??:?
#6  Foam::fvMatrix<double>::solve(Foam::dictionary const&) at ??:?
#7  Foam::NernstPlanck::correct() at ??:?
#8  ? at ??:?
#9  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#10  ? at ??:?
Floating point exception (core dumped)
```

**Comment by fppimenta** [comment]
By selecting the ‘steady-state’ ddt scheme you are removing the transient term from the NP equations and the matrix is no longer diagonally-dominant, even though you still keep under-relaxing ci by 0.1 (assuming you did not changed the value in the tutorial). This factor acts on the diagonal coefficients left, but because the problem is stiff, they become small upon removal of dc/dt. You would need to use a stronger under-relaxation in that case (smaller UR factor for ci; eg 0.001) to keep stability, but my advice is not to use the ‘steady-state’ scheme, even if you are only interested in the steady-state solution. Note however that advancing in time with the dc/dt term or using only under-relaxation to reach the steady solution are both valid methods and in fact they are interrelated (for cells of equal volume, one adds a constant term to the diagonal and the other adds coefficient-dependent terms).

**Comment by Beramos** [comment]
@fppimenta Increase the under-relaxation was the first thing I tried but you have to go down beyond 1e-5 to get it somewhat stable. I was hoping to speed up the 1D simulation by solving it steady-state but with such under-relaxation factors the simulation are as slow as the transient simulation. I'll stick to the transient simulations! Thanks for the advice and this amazing collection of OpenFOAM models!

**Comment by fppimenta** [comment]
I reopen this issue to say that the coupled solvers included in the newest rheoTool version (4.0) mitigate this issue. The 1D simulation can now be run without under-relaxation, using only time-stepping.

**Comment by fppimenta** [comment]
Yes. You can for example try it with 0.1 (under-relaxation factor for ci equations; psi does not need to be under-relaxed) and it will work (convergence in around 40 k iterations). I did not try higher under-relaxation factor, but perhaps it will still work. Running this 1D tutorial with steadyState is faster than with the current settings (Euler), which are just kept for consistency. But there are improvements even for Euler scheme, since we are now able to run the case without any under-relaxation (needed in previous version).

**Comment by Beramos** [comment]
Thank you very much for letting me know. I will close this issue now!
