### ISSUE TITLE
Rheofoam cylinder tutorial: different Cd 

### ISSUE THREAD

**Issue by lauguimel** [fppimenta/rheoTool#36]
Hello 
First of all, thank you very much for developing and sharing this tool. The documentation is very well written and makes it easy to use.

I am working on the cylinder in the channel and when running the tutorial with of60, I found Cd=117.649 instead of 117.357 as stated in the doc (and in literature). 

I tried to decrease the dt value and I found :

Delta Time | Drag Coefficient 
------------ | -------------
0,01 |  117,64941909 
0,001 | 117,665944642
0,0001 | 117,773294144

I also tried to refine the mesh (roughly 10% finer in each direction, for every region with dt=0.01) and found Cd=117.615 .

Do you know what may explain such difference ? May it be my rheotool installation ?

Thanks you for your help !

PS: To reproduce the results, I have set up a docker based on the of60 container containing rheotool that can be started by executing the the following script in the case directory:
[openfoam6-rheotool.txt](https://github.com/fppimenta/rheoTool/files/5552774/openfoam6-rheotool.txt)
Note that once in the container, environment variables must be sourced by executing `source /home/rheotool/envRheotool`

**Comment by fppimenta** [comment]
The answer is in Section 1.2 of the user-guide. The tutorials section in the user-guide is still mainly based on of 2.2.2 and the value reported was for that version of openfoam. If you have curiosity, you can go back to the initial commit and try it (dir of222). You will get this: 
[Cd.txt](https://github.com/fppimenta/rheoTool/files/5556731/Cd.txt)

The cd for the current version has changed from the value reported for several reasons. Firstly, because of 6.0 is free of several bugs which existed in of 2.2.2. I remember an important one related to non-ortho corrections in fvpatch. Secondly, because the numerics behind rheoTool also evolved. Also, small changes were introduced in the new versions of that tutorial (solver, BCs, ...). It happens that the cumulative effect of all these changes resulted in a new cd that is farther from the literature.

**Comment by lauguimel** [comment]
Thanks a lot for this very detailed answer, it confirms what I thought !
