### ISSUE TITLE
Correct path for EIGEN_REHO

### ISSUE THREAD

**Issue by gcapes** [fppimenta/rheoTool#4]
The docs seems to contradict themselves: 2.4 talks about setting `EIGEN_REHO`, but 2.5 says Eigen must be installed in a specified directory.

In any case, compiling with `EIGEN_REHO` set as suggested didn't work for me
```
wmake libso constitutiveEquations
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -isystem/opt/gridware/libs/eigen/3.2.1 -I/constitutiveEqs/utils -I/opt/gridware/apps/gcc/openfoam/6/OpenFOAM-6/src/finiteVolume/lnInclude -I/opt/gridware/apps/gcc/openfoam/6/OpenFOAM-6/src/meshTools/lnInclude -I/opt/gridware/apps/gcc/openfoam/6/OpenFOAM-6/src/transportModels/twoPhaseMixture/lnInclude -I/opt/gridware/apps/gcc/openfoam/6/OpenFOAM-6/src/transportModels/interfaceProperties/lnInclude  -IlnInclude -I. -I/opt/gridware/apps/gcc/openfoam/6/OpenFOAM-6/src/OpenFOAM/lnInclude -I/opt/gridware/apps/gcc/openfoam/6/OpenFOAM-6/src/OSspecific/POSIX/lnInclude   -fPIC -c constitutiveEqs/constitutiveEq/constitutiveEq.C -o Make/linux64GccDPInt32Opt/constitutiveEqs/constitutiveEq/constitutiveEq.o
constitutiveEqs/constitutiveEq/constitutiveEq.C:28:50: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense> // For eigen decomposition
                                                  ^
compilation terminated.
make: *** [Make/linux64GccDPInt32Opt/constitutiveEqs/constitutiveEq/constitutiveEq.o] Error 1
```
but instead I used
`export EIGEN_RHEO=/opt/gridware/libs/eigen/3.2.1/include/eigen3`

Perhaps this is Eigen version specific, but it would be worth including.

**Comment by fppimenta** [comment]
There should be no contradiction. Eigen can be downloaded and installed anywhere as long as the env variable EIGEN_RHEO is set to that path. After EIGEN_RHEO is assigned, Eigen can not be moved to other directory (unless $EIGEN_RHEO is also changed) and this is why we mention 'specified directory', in the sense 'static directory'. On the other hand, the folder containing rheoTool can be located/compiled anywhere and still be moved/compiled in a different directory after the first compilation.    

Note that you have misspelled EIGEN_REHO, which should be EIGEN_RHEO. Could be the reason of your error. The problem is not related with Eigen's version.

**Comment by fppimenta** [comment]
I will try to make it clearer in the user-guide.

The problem is definitely not due to Eigen's version. It seems just to be related with the way you get Eigen in your system. Looking to the path you have, I suppose you didn't wget Eigen (as suggested in the user-guide), but perhaps you apt install it, or your system already come with it. If so, the tree structure is different from when you download it (without install) and it is up to the user to ensure the correct path.
