### ISSUE TITLE
Tutorial Solution Error

### ISSUE THREAD

**Issue by javad-rahmannezhad** [fppimenta/rheoTool#84]
I have installed OpenFoam9 on my Ubuntu 22.04. The installation path is "home/professional/OpenFOAM".
Then I installed the Eigen and Petsc library successfully in this path: "home/professional/OpenFOAM/professional-9/Thirdparty". Finally, I have compiled rheoTool and I think it is compiled on this path:  "home/professional/OpenFOAM/professional-9/platforms". The installation finished with just one warning and no error.  
![image](https://user-images.githubusercontent.com/24921276/181409532-84fa1e92-d658-4c5a-ab34-9c44eaf09d65.png)
![image](https://user-images.githubusercontent.com/24921276/181409836-a47655b7-eff4-4e2a-9fcf-15affab4aa8e.png)

Unfortunately, when I try to run any of tutorials like rheoFoam/Channel or Cavity, I get this kind of error
![image](https://user-images.githubusercontent.com/24921276/181410046-b74bcf6e-0637-411e-8b62-01a502a2ba1b.png)

I have installed only v9 of the OpenFoam and this is the end of my ".bashrc" file:

source $HOME/OpenFOAM/OpenFOAM-9/etc/bashrc
export PATH=$PATH:/opt/Paraview-5.10/bin/
export EIGEN_RHEO=/home/professional/OpenFOAM/professional-9/ThirdParty/Eigen3.2.9
export PETSC_DIR=/home/professional/OpenFOAM/professional-9/ThirdParty/petsc-3.16.5
export PETSC_ARCH=arch-linux-c-opt
export LD_LIBRARY_PATH=$PETSC_DIR/$PETSC_ARCH/lib:$LD_LIBRARY_PATH

I would appreciate if you can help me.

**Comment by javad-rahmannezhad** [comment]
I have tested several tutorials and found that only tutorials which use log constitutive models are problematic on my system. However, I still don't know what's the reason for this situation?

**Comment by fppimenta** [comment]
Yes, I was able to reproduce the above mentioned error. I never tried ubuntu 22.04 before, nor the most recent of90 patch release ([20220602](https://github.com/OpenFOAM/OpenFOAM-9/releases/tag/20220602)), so that error never appear before.  I did the following tests:

 o ub22.04 + patch 20220602 = error
 o ub22.04 + patch 20211122 = error

o ub20.04 + patch 20220602 = ok
o ub20.04 + patch 20211122 = ok

So the issue is not in the openfoam patch, but in the os itself. More specifically, I believe it is in the gcc version, which changed from 9.4.0 to 11.2.0. However, I will need some time to figure out what is really going on.

Meanwhile, I don't recommend using rheotool in ub 22.04 (independently of using the log versions or not), as other kind of similar errors may exist. I would rather recommend to keep using ub 20.04 (fully-tested) or older. If the issue is on the gcc version, then compiling with gcc 9.4.0 in ub 22.04 might solve the issue, though I did not try this.

**Comment by javad-rahmannezhad** [comment]
Thank you for the help. I downgraded gcc to version 9 and it solved the problem.

**Comment by fppimenta** [comment]
I still didn't figure out the root of the problem, but I added a hotfix that seems to alleviate it: https://github.com/fppimenta/rheoTool/commit/79b7d362392a68c9c93ae82dfb5ba4f661db6c2d . This should be temporary until the issue is completely identified. For now, it seems to be associated to tmps and consecutive inner products, so perhaps with memory or some compiler optimization. Though, I would suggest to keep using gcc <= v9.4.0, as I don't know which other problems could still exist for recent compiler versions.

**Comment by renxiaosa00** [comment]
> 感谢您的详细测试和说明。在我们的帮助下，我将 gcc 降级到版本 9，它解决了 ub22.04 上的问题。

How to set the stl file to apply multiphase?

**Comment by fppimenta** [comment]
Stale.
