### ISSUE TITLE
custom installation dir

### ISSUE THREAD

**Issue by deniskristak** [fppimenta/rheoTool#85]
Hello,
I would love to know how I can change directory where libs and binaries are installed.
I have tried setting `WM_PROJECT_USER_DIR`, which didn't help at all.
I've also tried to set `FOAM_USER_APPBIN` and `FOAM_USER_LIBBIN`, but that resulted in errors during installation, such as
```undefined reference to `Foam::coupledSolver::typeName```

any idea how to proceed now?
Thank you

**Comment by fppimenta** [comment]
rheotool libs and execs go, as any other openfoam user code (by default), to FOAM_USER_APPBIN and FOAM_USER_LIBBIN. This is specified in all Make/files. You can change directly there, for each lib/exec, and add the new path to your PATH. The easiest way however is in fact to change the WM_PROJECT_USER_DIR. For that, go to the etc/bashrc file of openfoam and just change this line to whatever you like:
export WM_PROJECT_USER_DIR=$HOME/$WM_PROJECT/$USER-$WM_PROJECT_VERSION

Re-source that file and Allwclean -> Allwmake rheotool again. Note, that this will change the path for any future user applications you compile in openfoam, as well as the old ones you have (you need to move the .so and .exe for those, if you already have any, otherwise, they will not be found).

**Comment by boegel** [comment]
@fppimenta I tried modifying the `$WM_PROJECT_USER_DIR` environment variable *after* source OpenFOAM's `bashrc` to get control over where RheoTool gets installed, which doesn't work at all (it still goes into `$HOME/OpenFOAM-*/...`)... Is that expected?

**Comment by fppimenta** [comment]
Yes, that is the expected behavior. Libs and execs go to FOAM_USER_APPBIN and FOAM_USER_LIBBIN, which are set based upon WM_PROJECT_USER_DIR, in openfoam's etc/bashrc. If you just modify WM_PROJECT_USER_DIR in a shell, the other two vars will not get modified, as you can check it on vars. On the other hand, if you modify WM_PROJECT_USER_DIR directly in openfoam's etc/bashrc, then you ensure that they both will get the correct path. So if you just want to set the vars in a shell, and not in the bashrc, then set the three vars: WM_PROJECT_USER_DIR, FOAM_USER_APPBIN and FOAM_USER_LIBBIN (check your env before compilation to be sure that this is so). However, it is then up to you to add those to your path each time you need to compile/use something.

**Comment by deniskristak** [comment]
@fppimenta I did as you said - after sourcing $FOAM_BASH I ran `export WM_PROJECT_USER_DIR=somefolder`, then `export FOAM_USER_APPBIN=somefolder/bin`, and finally `export FOAM_USER_LIBBIN=somefolder/lib`.
I also tested it (echoed all three variables just before running `./Allwmake`.
now I'm getting aforementioned errors again
```lib/libEDFModels.so: undefined reference to `Foam::coupledTFvPatchScalarField::nbrFieldName() const'```

**Comment by fppimenta** [comment]
It's the linker for dynamic libs. The complete answer:

before compiling:

export WM_PROJECT_USER_DIR=somefolder
export FOAM_USER_APPBIN=somefolder/bin
export FOAM_USER_LIBBIN=somefolder/lib 
export LD_LIBRARY_PATH=somefolder/lib:$LD_LIBRARY_PATH

and before running any case:

export PATH=$FOAM_USER_APPBIN:$PATH
export LD_LIBRARY_PATH=$FOAM_USER_LIBBIN:$LD_LIBRARY_PATH

You can of course put this somewhere and load it on demand.
